apiVersion: rivtower.com/v1cita
kind: Backup
metadata:
  name: state-backup-to-s3
  namespace: app-rivspace
spec:
  node: chain-800049219682570240-0
  deployMethod: python
  action: StopAndStart
  chain: chain-800049219682570240
  dataType:
    state:
      blockHeight: 50

  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
#  tags:
#    - test
#    - dump
#    - mariadb
  backend:
    repoPasswordSecretRef:
      name: backup-repo
      key: password
    s3:
#      endpoint: http://192.168.31.200:31026
      endpoint: http://192.168.10.122:30289
      bucket: k8up-state
      accessKeyIDSecretRef:
        name: minio-credentials
        key: username
      secretAccessKeySecretRef:
        name: minio-credentials
        key: password
