apiVersion: rivtower.com/v1cita
kind: Backup
metadata:
  name: full-backup-to-s3
  namespace: app-rivspace
spec:
  node: chain-800049219682570240-0
  deployMethod: python
  chain: chain-800049219682570240
  dataType:
    full:
      includePaths:
        - "data"
        - "chain_data"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: backup-repo
      key: password
    s3:
      endpoint: http://192.168.10.122:30289
      bucket: k8up-full
      accessKeyIDSecretRef:
        name: minio-credentials
        key: username
      secretAccessKeySecretRef:
        name: minio-credentials
        key: password
