---
apiVersion: rivtower.com/v1cita
kind: Schedule
metadata:
  name: schedule-test
  namespace: zhujq
spec:
  chain: test-chain-zenoh-overlord
  node: test-chain-zenoh-overlord-node0
  deployMethod: cloud-config
  resourceRequirementsTemplate:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  backend:
    repoPasswordSecretRef:
      name: backup-repo
      key: password
    s3:
      endpoint: http://192.168.10.122:30289
      bucket: k8up-full
      accessKeyIDSecretRef:
        name: minio-credentials
        key: username
      secretAccessKeySecretRef:
        name: minio-credentials
        key: password
  citaBackup:
    schedule: '52 14 * * *'
    dataType:
      full:
        includePaths:
          - "data"
          - "chain_data"
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
