apiVersion: rivtower.com/v1cita
kind: BlockHeightFallback
metadata:
  name: fallback-sample
  namespace: zhujq
spec:
  blockHeight: 116000
  node: test-chain-zenoh-overlord-node0
  action: StopAndStart
  deployMethod: cloud-config
  chain: test-chain-zenoh-overlord

