apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: state-backup-to-s3
  namespace: zhujq
spec:
  node: test-chain-zenoh-overlord-node0
  chain: test-chain-zenoh-overlord
  dataType:
    state:
      blockHeight: 50

  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
#  tags:
#    - test
#    - dump
#    - mariadb
  backend:
    repoPasswordSecretRef:
      name: backup-repo
      key: password
    s3:
#      endpoint: http://192.168.31.200:31026
      endpoint: http://192.168.10.122:30289
      bucket: k8up-state
      accessKeyIDSecretRef:
        name: minio-credentials
        key: username
      secretAccessKeySecretRef:
        name: minio-credentials
        key: password
